# Generated by Django 5.1.6 on 2025-02-23 09:42

import applications.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_branch_city_customuser_is_paid_customuser_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', validators=[applications.validators.validate_file_extension], verbose_name='Hujjat')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('status', models.CharField(choices=[("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ('Qabul qilindi', 'Qabul qilindi'), ('Rad etildi', 'Rad etildi')], max_length=100, verbose_name='Holat')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Rad etish sababi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Filial')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.city', verbose_name='Shahar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(to='applications.document', verbose_name='Hujjatlar')),
            ],
        ),
    ]
