# Generated by Django 5.1.6 on 2025-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='time_to_come',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vaqtni belgilash'),
        ),
    ]
