# Generated by Django 5.1.6 on 2025-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_time_to_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil'),
        ),
    ]
