# Generated by Django 5.1.6 on 2025-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(related_name='applications', to='applications.document', verbose_name='Hujjatlar'),
        ),
    ]
