# Generated by Django 5.1.6 on 2025-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_city_customuser_is_paid_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('bank_operator', 'Bank Operator'), ('government_officer', 'Davlat Xodimi'), ('branch_admin', 'Filial Admin'), ('admin', 'Admin'), ('branch_boss', "Filial boshlig'i"), ('customer', 'Foydalanuvchi')], default='customer', max_length=20),
        ),
    ]
