# Generated by Django 5.1.6 on 2025-02-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('bank_operator', 'Bank Operator'), ('government_officer', 'Davlat Xodimi'), ('branch_admin', 'Filial Admin'), ('admin', 'Admin'), ('branch_boss', "Filial boshlig'i"), ('customer', 'Foydalanuvchi')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.TextField(null=True, blank=True),
        ),
    ]
