# Generated by Django 5.1.6 on 2025-03-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
